Support `ClassDef` with a base class containing attributes.
Before this modification `ClassDef("Cls1").base("module.Base").to_cst()` would raise the following error :
```
libcst._nodes.base.CSTValidationError: Name 'module.Base' is not a valid identifier.
```

In such case, we need to use an `Attribute` instead of a `Name`.